export const DEPARTMENT_LIST_REQUEST = "DEPARTMENT_LIST_REQUEST";
export const DEPARTMENT_LIST_SUCCESS = "DEPARTMENT_LIST_SUCCESS";
export const DEPARTMENT_LIST_FAIL = "DEPARTMENT_LIST_FAIL";

export const DEPARTMENT_ADD_REQUEST = "DEPARTMENT_ADD_REQUEST";
export const DEPARTMENT_ADD_SUCCESS = "DEPARTMENT_ADD_SUCCESS";
export const DEPARTMENT_ADD_FAIL = "DEPARTMENT_ADD_FAIL";

export const DEPARTMENT_DELETE_REQUEST = "DEPARTMENT_DELETE_REQUEST";
export const DEPARTMENT_DELETE_SUCCESS = "DEPARTMENT_DELETE_SUCCESS";
export const DEPARTMENT_DELETE_FAIL = "DEPARTMENT_DELETE_FAIL";
