export const DESIGNATION_LIST_REQUEST = "DESIGNATION_LIST_REQUEST";
export const DESIGNATION_LIST_SUCCESS = "DESIGNATION_LIST_SUCCESS";
export const DESIGNATION_LIST_FAIL = "DESIGNATION_LIST_FAIL";

export const DESIGNATION_ADD_REQUEST = "DESIGNATION_ADD_REQUEST";
export const DESIGNATION_ADD_SUCCESS = "DESIGNATION_ADD_SUCCESS";
export const DESIGNATION_ADD_FAIL = "DESIGNATION_ADD_FAIL";

export const DESIGNATION_DELETE_REQUEST = "DESIGNATION_DELETE_REQUEST";
export const DESIGNATION_DELETE_SUCCESS = "DESIGNATION_DELETE_SUCCESS";
export const DESIGNATION_DELETE_FAIL = "DESIGNATION_DELETE_FAIL";
