export const WARDEN_LIST_REQUEST = "WARDEN_LIST_REQUEST";
export const WARDEN_LIST_SUCCESS = "WARDEN_LIST_SUCCESS";
export const WARDEN_LIST_FAIL = "WARDEN_LIST_FAIL";

export const WARDEN_ADD_REQUEST = "WARDEN_ADD_REQUEST";
export const WARDEN_ADD_SUCCESS = "WARDEN_ADD_SUCCESS";
export const WARDEN_ADD_FAIL = "WARDEN_ADD_FAIL";

export const WARDEN_DELETE_REQUEST = "WARDEN_DELETE_REQUEST";
export const WARDEN_DELETE_SUCCESS = "WARDEN_DELETE_SUCCESS";
export const WARDEN_DELETE_FAIL = "WARDEN_DELETE_FAIL";
